# Satish Agrawal
### Bellevue University
### DSC 540 -- Milestone 4

In [1]:
# Load required binaries
import numpy as np
import array as arr
import pandas as pd
import matplotlib.pyplot as plt
import requests as req
import json

## Load the data from API

In [2]:
# choose the right url
url = "http://api.marketcheck.com/v2/popular/cars?api_key=Gd0O9xOsyxlYrAXWdjthINZEVFX7K9Gc&car_type=used"
url2 = 'http://api.marketcheck.com/v2/search/car/active?api_key=Gd0O9xOsyxlYrAXWdjthINZEVFX7K9Gc&car_type=used'

# supply appropriate headers
header = {'Host':'marketcheck-prod.apigee.net'}

# Call the service 
response = req.get(url, headers = header)

In [3]:
response

In [4]:
# type of the response
type(response)

requests.models.Response

In [5]:
def status_check(r):
    if r.status_code == 200:
        print("Success!")
        return 1
    else:
        print("Fail!")
        return -1

# check the status of the response    
status_check(response)

Success!

1

In [6]:
def encoding_check(r):
    return r.encoding

# confirm the encoding of response
encoding_check(response)

'utf-8'

In [7]:
# decode the content to string
content = response.content.decode(encoding_check(response))
type(content)

str

In [8]:
# review the content which is string now but is well formed json
content

'[{"country":"us","inventory_type":"used","count":102767,"make":"Ford","model":"F-150","price_stats":{"geometric_mean":22934,"listings_count":90156,"min":499,"median":26450,"population_standard_deviation":11368,"variance":129241702,"max":409905,"mean":25821,"trimmed_mean":25545,"standard_deviation":11368,"iqr":14195},"miles_stats":{"geometric_mean":49392,"listings_count":98269,"min":1,"median":60062,"population_standard_deviation":57017,"variance":3250942079,"max":1406720,"mean":74231,"trimmed_mean":67610,"standard_deviation":57017,"iqr":75920},"dom_stats":{"geometric_mean":68,"listings_count":102767,"min":1,"median":80,"population_standard_deviation":158,"variance":24894,"max":2429,"mean":124,"trimmed_mean":96,"standard_deviation":158,"iqr":119}},{"country":"us","inventory_type":"used","count":75449,"make":"Chevrolet","model":"Silverado 1500","price_stats":{"geometric_mean":22927,"listings_count":66864,"min":495,"median":25995,"population_standard_deviation":9249,"variance":85543903,"max":399008,"mean":24983,"trimmed_mean":25083,"standard_deviation":9249,"iqr":11801},"miles_stats":{"geometric_mean":50173,"listings_count":72336,"min":1,"median":58000,"population_standard_deviation":55229,"variance":3050218372,"max":1916551,"mean":72399,"trimmed_mean":65730,"standard_deviation":55229,"iqr":70456},"dom_stats":{"geometric_mean":77,"listings_count":75449,"min":1,"median":93,"population_standard_deviation":162,"variance":26316,"max":2514,"mean":134,"trimmed_mean":107,"standard_deviation":162,"iqr":127}},{"country":"us","inventory_type":"used","count":55030,"make":"Ford","model":"Escape","price_stats":{"geometric_mean":14049,"listings_count":48757,"min":499,"median":15495,"population_standard_deviation":7040,"variance":49554836,"max":999999,"mean":15145,"trimmed_mean":15170,"standard_deviation":7040,"iqr":6005},"miles_stats":{"geometric_mean":42128,"listings_count":52801,"min":1,"median":45491,"population_standard_deviation":47654,"variance":2270912620,"max":2000401,"mean":60291,"trimmed_mean":54471,"standard_deviation":47654,"iqr":57872},"dom_stats":{"geometric_mean":65,"listings_count":55030,"min":1,"median":77,"population_standard_deviation":147,"variance":21695,"max":2371,"mean":114,"trimmed_mean":89,"standard_deviation":147,"iqr":104}},{"country":"us","inventory_type":"used","count":53625,"make":"Toyota","model":"Camry","price_stats":{"geometric_mean":13956,"listings_count":47486,"min":499,"median":15999,"population_standard_deviation":7837,"variance":61418365,"max":799993,"mean":15342,"trimmed_mean":15357,"standard_deviation":7837,"iqr":6834},"miles_stats":{"geometric_mean":44454,"listings_count":51672,"min":1,"median":44810,"population_standard_deviation":54816,"variance":3004779625,"max":1915941,"mean":64964,"trimmed_mean":56673,"standard_deviation":54816,"iqr":63872},"dom_stats":{"geometric_mean":48,"listings_count":53625,"min":1,"median":58,"population_standard_deviation":129,"variance":16709,"max":2324,"mean":90,"trimmed_mean":68,"standard_deviation":129,"iqr":84}},{"country":"us","inventory_type":"used","count":49430,"make":"Chevrolet","model":"Equinox","price_stats":{"geometric_mean":14853,"listings_count":44495,"min":499,"median":16000,"population_standard_deviation":7080,"variance":50132603,"max":999999,"mean":15868,"trimmed_mean":15824,"standard_deviation":7080,"iqr":6555},"miles_stats":{"geometric_mean":41781,"listings_count":47579,"min":1,"median":44180,"population_standard_deviation":44752,"variance":2002699545,"max":1914712,"mean":57718,"trimmed_mean":52246,"standard_deviation":44752,"iqr":59882},"dom_stats":{"geometric_mean":63,"listings_count":49430,"min":1,"median":74,"population_standard_deviation":139,"variance":19305,"max":2255,"mean":106,"trimmed_mean":83,"standard_deviation":139,"iqr":95}},{"country":"us","inventory_type":"used","count":49357,"make":"RAM","model":"Ram 1500 Pickup","price_stats":{"geometric_mean":24763,"listings_count":45051,"min":1995,"median":25793,"population_standard_deviation":8092,"variance":65472734,"max":389009,"mean":25918,"trimmed_mean":25575,"standard_deviation":8092,"iqr":9196},"miles_stats":{"geometric_mean":39973,"listings_count":47561,"min":1,"median":45793,"population_standard_deviation":41083,"variance":1687781680,"max":1908941,"mean":56097,"trimmed_mean":51511,"standard_deviation":41083,"iqr":54870},"dom_stats":{"geometric_mean":96,"listings_count":49357,"min":1,"median":110,"population_standard_deviation":158,"variance":24886,"max":2396,"mean":150,"trimmed_mean":125,"standard_deviation":158,"iqr":140}},{"country":"us","inventory_type":"used","count":49294,"make":"Nissan","model":"Rogue","price_stats":{"geometric_mean":16133,"listings_count":45376,"min":1130,"median":16998,"population_standard_deviation":4436,"variance":19677873,"max":243914,"mean":16770,"trimmed_mean":16940,"standard_deviation":4436,"iqr":4017},"miles_stats":{"geometric_mean":33383,"listings_count":47837,"min":1,"median":36297,"population_standard_deviation":31994,"variance":1023616849,"max":1240060,"mean":44173,"trimmed_mean":39409,"standard_deviation":31994,"iqr":26149},"dom_stats":{"geometric_mean":55,"listings_count":49294,"min":1,"median":64,"population_standard_deviation":117,"variance":13648,"max":2257,"mean":94,"trimmed_mean":75,"standard_deviation":117,"iqr":90}},{"country":"us","inventory_type":"used","count":48024,"make":"Honda","model":"Accord","price_stats":{"geometric_mean":13813,"listings_count":41990,"min":399,"median":15997,"population_standard_deviation":9279,"variance":86093467,"max":999999,"mean":15435,"trimmed_mean":15433,"standard_deviation":9279,"iqr":8394},"miles_stats":{"geometric_mean":46723,"listings_count":45915,"min":1,"median":49933,"population_standard_deviation":60372,"variance":3644781500,"max":2005674,"mean":70245,"trimmed_mean":61926,"standard_deviation":60372,"iqr":72547},"dom_stats":{"geometric_mean":52,"listings_count":48024,"min":1,"median":63,"population_standard_deviation":140,"variance":19495,"max":2446,"mean":100,"trimmed_mean":75,"standard_deviation":140,"iqr":94}},{"country":"us","inventory_type":"used","count":46872,"make":"Honda","model":"CR-V","price_stats":{"geometric_mean":16137,"listings_count":43170,"min":573,"median":17870,"population_standard_deviation":8934,"variance":79820392,"max":999999,"mean":17418,"trimmed_mean":17479,"standard_deviation":8934,"iqr":7202},"miles_stats":{"geometric_mean":42629,"listings_count":45073,"min":1,"median":42772,"population_standard_deviation":50404,"variance":2540589654,"max":1908491,"mean":61005,"trimmed_mean":53660,"standard_deviation":50404,"iqr":58145},"dom_stats":{"geometric_mean":53,"listings_count":46872,"min":1,"median":61,"population_standard_deviation":118,"variance":13916,"max":2326,"mean":90,"trimmed_mean":71,"standard_deviation":118,"iqr":82}},{"country":"us","inventory_type":"used","count":46053,"make":"Nissan","model":"Altima","price_stats":{"geometric_mean":12902,"listings_count":39721,"min":495,"median":14558,"population_standard_deviation":4538,"variance":20590673,"max":100000,"mean":13815,"trimmed_mean":14037,"standard_deviation":4538,"iqr":4003},"miles_stats":{"geometric_mean":44369,"listings_count":44204,"min":1,"median":45294,"population_standard_deviation":44410,"variance":1972279122,"max":999999,"mean":59740,"trimmed_mean":53070,"standard_deviation":44410,"iqr":41317},"dom_stats":{"geometric_mean":55,"listings_count":46053,"min":1,"median":64,"population_standard_deviation":141,"variance":20001,"max":2329,"mean":103,"trimmed_mean":79,"standard_deviation":141,"iqr":101}},{"country":"us","inventory_type":"used","count":44675,"make":"Toyota","model":"RAV4","price_stats":{"geometric_mean":18145,"listings_count":41608,"min":1100,"median":19699,"population_standard_deviation":12142,"variance":147438725,"max":999999,"mean":19242,"trimmed_mean":19407,"standard_deviation":12142,"iqr":5690},"miles_stats":{"geometric_mean":35364,"listings_count":43278,"min":1,"median":35845,"population_standard_deviation":45788,"variance":2096495945,"max":2000741,"mean":49643,"trimmed_mean":42300,"standard_deviation":45788,"iqr":36600},"dom_stats":{"geometric_mean":52,"listings_count":44675,"min":1,"median":60,"population_standard_deviation":104,"variance":10747,"max":1927,"mean":83,"trimmed_mean":68,"standard_deviation":104,"iqr":75}},{"country":"us","inventory_type":"used","count":44237,"make":"Toyota","model":"Corolla","price_stats":{"geometric_mean":12512,"listings_count":39739,"min":799,"median":13991,"population_standard_deviation":9494,"variance":90128540,"max":999999,"mean":13289,"trimmed_mean":13521,"standard_deviation":9494,"iqr":3634},"miles_stats":{"geometric_mean":38629,"listings_count":42758,"min":1,"median":40178,"population_standard_deviation":49722,"variance":2472324200,"max":2999999,"mean":54731,"trimmed_mean":46821,"standard_deviation":49722,"iqr":44992},"dom_stats":{"geometric_mean":47,"listings_count":44237,"min":1,"median":56,"population_standard_deviation":119,"variance":14056,"max":2514,"mean":85,"trimmed_mean":66,"standard_deviation":119,"iqr":81}},{"country":"us","inventory_type":"used","count":43944,"make":"Honda","model":"Civic","price_stats":{"geometric_mean":12607,"listings_count":38809,"min":399,"median":14981,"population_standard_deviation":6248,"variance":39034016,"max":788894,"mean":13793,"trimmed_mean":14041,"standard_deviation":6248,"iqr":6296},"miles_stats":{"geometric_mean":41682,"listings_count":42017,"min":1,"median":42000,"population_standard_deviation":53226,"variance":2832977369,"max":1916361,"mean":61708,"trimmed_mean":53559,"standard_deviation":53226,"iqr":60255},"dom_stats":{"geometric_mean":48,"listings_count":43944,"min":1,"median":56,"population_standard_deviation":128,"variance":16395,"max":2100,"mean":89,"trimmed_mean":67,"standard_deviation":128,"iqr":81}},{"country":"us","inventory_type":"used","count":42743,"make":"Jeep","model":"Grand Cherokee","price_stats":{"geometric_mean":20923,"listings_count":38037,"min":350,"median":24350,"population_standard_deviation":12560,"variance":157758860,"max":999999,"mean":23658,"trimmed_mean":23621,"standard_deviation":12560,"iqr":12754},"miles_stats":{"geometric_mean":43991,"listings_count":40840,"min":1,"median":47874,"population_standard_deviation":50205,"variance":2520492651,"max":1460583,"mean":64001,"trimmed_mean":57425,"standard_deviation":50205,"iqr":63875},"dom_stats":{"geometric_mean":76,"listings_count":42743,"min":1,"median":93,"population_standard_deviation":154,"variance":23745,"max":2346,"mean":131,"trimmed_mean":105,"standard_deviation":154,"iqr":123}},{"country":"us","inventory_type":"used","count":41544,"make":"Ford","model":"Explorer","price_stats":{"geometric_mean":20666,"listings_count":36765,"min":399,"median":23998,"population_standard_deviation":10374,"variance":107625898,"max":999999,"mean":23138,"trimmed_mean":23382,"standard_deviation":10374,"iqr":12669},"miles_stats":{"geometric_mean":48029,"listings_count":39773,"min":1,"median":50838,"population_standard_deviation":49002,"variance":2401165299,"max":999999,"mean":66210,"trimmed_mean":59641,"standard_deviation":49002,"iqr":62352},"dom_stats":{"geometric_mean":62,"listings_count":41544,"min":1,"median":72,"population_standard_deviation":152,"variance":23173,"max":2340,"mean":111,"trimmed_mean":84,"standard_deviation":152,"iqr":100}},{"country":"us","inventory_type":"used","count":34689,"make":"Ford","model":"Fusion","price_stats":{"geometric_mean":12218,"listings_count":29955,"min":700,"median":13481,"population_standard_deviation":7412,"variance":54934746,"max":999999,"mean":13193,"trimmed_mean":13150,"standard_deviation":7412,"iqr":6003},"miles_stats":{"geometric_mean":48131,"listings_count":33188,"min":1,"median":56000,"population_standard_deviation":48257,"variance":2328764720,"max":2000000,"mean":65646,"trimmed_mean":60869,"standard_deviation":48257,"iqr":60158},"dom_stats":{"geometric_mean":66,"listings_count":34689,"min":1,"median":78,"population_standard_deviation":167,"variance":28008,"max":2514,"mean":123,"trimmed_mean":92,"standard_deviation":167,"iqr":116}},{"country":"us","inventory_type":"used","count":33141,"make":"Nissan","model":"Sentra","price_stats":{"geometric_mean":11526,"listings_count":29204,"min":537,"median":12499,"population_standard_deviation":7037,"variance":49516535,"max":850056,"mean":12126,"trimmed_mean":12243,"standard_deviation":7037,"iqr":3392},"miles_stats":{"geometric_mean":33399,"listings_count":31989,"min":1,"median":40251,"population_standard_deviation":38841,"variance":1508598199,"max":2100001,"mean":47694,"trimmed_mean":42371,"standard_deviation":38841,"iqr":32464},"dom_stats":{"geometric_mean":54,"listings_count":33141,"min":1,"median":65,"population_standard_deviation":132,"variance":17420,"max":2319,"mean":99,"trimmed_mean":76,"standard_deviation":132,"iqr":96}},{"country":"us","inventory_type":"used","count":31961,"make":"Chevrolet","model":"Malibu","price_stats":{"geometric_mean":12367,"listings_count":27225,"min":495,"median":14200,"population_standard_deviation":7923,"variance":62778634,"max":999999,"mean":13472,"trimmed_mean":13566,"standard_deviation":7923,"iqr":5733},"miles_stats":{"geometric_mean":47368,"listings_count":30456,"min":1,"median":47779,"population_standard_deviation":46110,"variance":2126113581,"max":1177961,"mean":63687,"trimmed_mean":57868,"standard_deviation":46110,"iqr":55630},"dom_stats":{"geometric_mean":65,"listings_count":31961,"min":1,"median":79,"population_standard_deviation":165,"variance":27164,"max":2502,"mean":122,"trimmed_mean":93,"standard_deviation":165,"iqr":116}},{"country":"us","inventory_type":"used","count":31404,"make":"Hyundai","model":"Elantra","price_stats":{"geometric_mean":11720,"listings_count":27581,"min":350,"median":12977,"population_standard_deviation":4473,"variance":20007945,"max":399590,"mean":12306,"trimmed_mean":12476,"standard_deviation":4473,"iqr":3299},"miles_stats":{"geometric_mean":39070,"listings_count":29988,"min":1,"median":41777,"population_standard_deviation":38302,"variance":1467080253,"max":999999,"mean":51745,"trimmed_mean":46373,"standard_deviation":38302,"iqr":39788},"dom_stats":{"geometric_mean":54,"listings_count":31404,"min":1,"median":63,"population_standard_deviation":133,"variance":17573,"max":2347,"mean":98,"trimmed_mean":76,"standard_deviation":133,"iqr":94}},{"country":"us","inventory_type":"used","count":30625,"make":"Toyota","model":"Tacoma","price_stats":{"geometric_mean":23260,"listings_count":28098,"min":1325,"median":26448,"population_standard_deviation":11904,"variance":141695050,"max":999999,"mean":24940,"trimmed_mean":25301,"standard_deviation":11904,"iqr":10968},"miles_stats":{"geometric_mean":38257,"listings_count":29564,"min":1,"median":41504,"population_standard_deviation":57644,"variance":3322837092,"max":1910811,"mean":61691,"trimmed_mean":52501,"standard_deviation":57644,"iqr":66447},"dom_stats":{"geometric_mean":57,"listings_count":30625,"min":1,"median":67,"population_standard_deviation":125,"variance":15516,"max":2152,"mean":96,"trimmed_mean":75,"standard_deviation":125,"iqr":86}},{"country":"us","inventory_type":"used","count":29842,"make":"Ford","model":"Focus","price_stats":{"geometric_mean":9633,"listings_count":24995,"min":400,"median":10599,"population_standard_deviation":10056,"variance":101128513,"max":999999,"mean":10699,"trimmed_mean":10379,"standard_deviation":10056,"iqr":5189},"miles_stats":{"geometric_mean":50167,"listings_count":28387,"min":1,"median":53610,"population_standard_deviation":45083,"variance":2032470490,"max":999999,"mean":65804,"trimmed_mean":60520,"standard_deviation":45083,"iqr":56797},"dom_stats":{"geometric_mean":62,"listings_count":29842,"min":1,"median":75,"population_standard_deviation":176,"variance":30882,"max":2349,"mean":125,"trimmed_mean":91,"standard_deviation":176,"iqr":118}},{"country":"us","inventory_type":"used","count":29512,"make":"Dodge","model":"Grand Caravan","price_stats":{"geometric_mean":14751,"listings_count":25807,"min":600,"median":16998,"population_standard_deviation":8262,"variance":68259372,"max":999999,"mean":16031,"trimmed_mean":16259,"standard_deviation":8262,"iqr":5490},"miles_stats":{"geometric_mean":47190,"listings_count":28302,"min":1,"median":45351,"population_standard_deviation":44266,"variance":1959489882,"max":494159,"mean":60712,"trimmed_mean":53434,"standard_deviation":44266,"iqr":42749},"dom_stats":{"geometric_mean":44,"listings_count":29512,"min":1,"median":52,"population_standard_deviation":130,"variance":16814,"max":2324,"mean":84,"trimmed_mean":61,"standard_deviation":130,"iqr":73}},{"country":"us","inventory_type":"used","count":29389,"make":"GMC","model":"Sierra 1500","price_stats":{"geometric_mean":24451,"listings_count":26048,"min":650,"median":26995,"population_standard_deviation":9935,"variance":98698887,"max":346509,"mean":26603,"trimmed_mean":26663,"standard_deviation":9935,"iqr":13541},"miles_stats":{"geometric_mean":48596,"listings_count":28189,"min":1,"median":57843,"population_standard_deviation":53654,"variance":2878786407,"max":2000941,"mean":70077,"trimmed_mean":63648,"standard_deviation":53654,"iqr":69160},"dom_stats":{"geometric_mean":78,"listings_count":29389,"min":1,"median":93,"population_standard_deviation":157,"variance":24771,"max":2265,"mean":134,"trimmed_mean":107,"standard_deviation":157,"iqr":126}},{"country":"us","inventory_type":"used","count":27772,"make":"Jeep","model":"Cherokee","price_stats":{"geometric_mean":18294,"listings_count":26024,"min":750,"median":18683,"population_standard_deviation":4622,"variance":21362878,"max":99995,"mean":18911,"trimmed_mean":18789,"standard_deviation":4622,"iqr":5709},"miles_stats":{"geometric_mean":31840,"listings_count":26837,"min":1,"median":36630,"population_standard_deviation":32117,"variance":1031516844,"max":372756,"mean":43958,"trimmed_mean":40028,"standard_deviation":32117,"iqr":35495},"dom_stats":{"geometric_mean":90,"listings_count":27772,"min":1,"median":103,"population_standard_deviation":138,"variance":18952,"max":1992,"mean":137,"trimmed_mean":116,"standard_deviation":138,"iqr":126}},{"country":"us","inventory_type":"used","count":27342,"make":"Ford","model":"Edge","price_stats":{"geometric_mean":17075,"listings_count":24543,"min":900,"median":19200,"population_standard_deviation":7549,"variance":56983525,"max":336153,"mean":18710,"trimmed_mean":18618,"standard_deviation":7549,"iqr":10997},"miles_stats":{"geometric_mean":45765,"listings_count":26305,"min":1,"median":48834,"population_standard_deviation":46522,"variance":2164253872,"max":999999,"mean":64349,"trimmed_mean":59045,"standard_deviation":46522,"iqr":63190},"dom_stats":{"geometric_mean":70,"listings_count":27342,"min":1,"median":80,"population_standard_deviation":160,"variance":25445,"max":2436,"mean":122,"trimmed_mean":94,"standard_deviation":160,"iqr":110}},{"country":"us","inventory_type":"used","count":26465,"make":"Chevrolet","model":"Cruze","price_stats":{"geometric_mean":11256,"listings_count":23222,"min":573,"median":12249,"population_standard_deviation":9937,"variance":98750167,"max":999999,"mean":11920,"trimmed_mean":11861,"standard_deviation":9937,"iqr":5263},"miles_stats":{"geometric_mean":42136,"listings_count":25443,"min":1,"median":46509,"population_standard_deviation":40016,"variance":1601240478,"max":1346430,"mean":56925,"trimmed_mean":53127,"standard_deviation":40016,"iqr":56484},"dom_stats":{"geometric_mean":77,"listings_count":26465,"min":1,"median":90,"population_standard_deviation":172,"variance":29657,"max":2423,"mean":135,"trimmed_mean":104,"standard_deviation":172,"iqr":123}},{"country":"us","inventory_type":"used","count":25740,"make":"Toyota","model":"Highlander","price_stats":{"geometric_mean":22228,"listings_count":23782,"min":1200,"median":26495,"population_standard_deviation":8910,"variance":79389483,"max":288881,"mean":24383,"trimmed_mean":24956,"standard_deviation":8910,"iqr":11222},"miles_stats":{"geometric_mean":43508,"listings_count":24927,"min":1,"me

In [9]:
# convert the response string to a json object
json_data = response.json()
type(json_data)

list

In [10]:
# convert json object to a data frame
df = pd.DataFrame(json_data)

# it looks like nested elements are not normalized to individual columns
df

,country,inventory_type,count,make,model,price_stats,miles_stats,dom_stats
0,us,used,102767,Ford,F-150,"{'geometric_mean': 22934, 'listings_count': 90...","{'geometric_mean': 49392, 'listings_count': 98...","{'geometric_mean': 68, 'listings_count': 10276..."
1,us,used,75449,Chevrolet,Silverado 1500,"{'geometric_mean': 22927, 'listings_count': 66...","{'geometric_mean': 50173, 'listings_count': 72...","{'geometric_mean': 77, 'listings_count': 75449..."
2,us,used,55030,Ford,Escape,"{'geometric_mean': 14049, 'listings_count': 48...","{'geometric_mean': 42128, 'listings_count': 52...","{'geometric_mean': 65, 'listings_count': 55030..."
3,us,used,53625,Toyota,Camry,"{'geometric_mean': 13956, 'listings_count': 47...","{'geometric_mean': 44454, 'listings_count': 51...","{'geometric_mean': 48, 'listings_count': 53625..."
4,us,used,49430,Chevrolet,Equinox,"{'geometric_mean': 14853, 'listings_count': 44...","{'geometric_mean': 41781, 'listings_count': 47...","{'geometric_mean': 63, 'listings_count': 49430..."
5,us,used,49357,RAM,Ram 1500 Pickup,"{'geometric_mean': 24763, 'listings_count': 45...","{'geometric_mean': 39973, 'listings_count': 47...","{'geometric_mean': 96, 'listings_count': 49357..."
6,us,used,49294,Nissan,Rogue,"{'geometric_mean': 16133, 'listings_count': 45...","{'geometric_mean': 33383, 'listings_count': 47...","{'geometric_mean': 55, 'listings_count': 49294..."
7,us,used,48024,Honda,Accord,"{'geometric_mean': 13813, 'listings_count': 41...","{'geometric_mean': 46723, 'listings_count': 45...","{'geometric_mean': 52, 'listings_count': 48024..."
8,us,used,46872,Honda,CR-V,"{'geometric_mean': 16137, 'listings_count': 43...","{'geometric_mean': 42629, 'listings_count': 45...","{'geometric_mean': 53, 'listings_count': 46872..."
9,us,used,46053,Nissan,Altima,"{'geometric_mean': 12902, 'listings_count': 39...","{'geometric_mean': 44369, 'listings_count': 44...","{'geometric_mean': 55, 'listings_count': 46053..."
10,us,used,44675,Toyota,RAV4,"{'geometric_mean': 18145, 'listings_count': 41...","{'geometric_mean': 35364, 'listings_count': 43...","{'geometric_mean': 52, 'listings_count': 44675..."
11,us,used,44237,Toyota,Corolla,"{'geometric_mean': 12512, 'listings_count': 39...","{'geometric_mean': 38629, 'listings_count': 42...","{'geometric_mean': 47, 'listings_count': 44237..."
12,us,used,43944,Honda,Civic,"{'geometric_mean': 12607, 'listings_count': 38...","{'geometric_mean': 41682, 'listings_count': 42...","{'geometric_mean': 48, 'listings_count': 43944..."
13,us,used,42743,Jeep,Grand Cherokee,"{'geometric_mean': 20923, 'listings_count': 38...","{'geometric_mean': 43991, 'listings_count': 40...","{'geometric_mean': 76, 'listings_count': 42743..."
14,us,used,41544,Ford,Explorer,"{'geometric_mean': 20666, 'listings_count': 36...","{'geometric_mean': 48029, 'listings_count': 39...","{'geometric_mean': 62, 'listings_count': 41544..."
15,us,used,34689,Ford,Fusion,"{'geometric_mean': 12218, 'listings_count': 29...","{'geometric_mean': 48131, 'listings_count': 33...","{'geometric_mean': 66, 'listings_count': 34689..."
16,us,used,33141,Nissan,Sentra,"{'geometric_mean': 11526, 'listings_count': 29...","{'geometric_mean': 33399, 'listings_count': 31...","{'geometric_mean': 54, 'listings_count': 33141..."
17,us,used,31961,Chevrolet,Malibu,"{'geometric_mean': 12367, 'listings_count': 27...","{'geometric_mean': 47368, 'listings_count': 30...","{'geometric_mean': 65, 'listings_count': 31961..."
18,us,used,31404,Hyundai,Elantra,"{'geometric_mean': 11720, 'listings_count': 27...","{'geometric_mean': 39070, 'listings_count': 29...","{'geometric_mean': 54, 'listings_count': 31404..."
19,us,used,30625,Toyota,Tacoma,"{'geometric_mean': 23260, 'listings_count': 28...","{'geometric_mean': 38257, 'listings_count': 29...","{'geometric_mean': 57, 'listings_count': 30625..."
20,us,used,29842,Ford,Focus,"{'geometric_mean': 9633, 'listings_count': 249...","{'geometric_mean': 50167, 'listings_count': 28...","{'geometric_mean': 62, 'listings_count': 29842..."
21,us,used,29512,Dodge,Grand Caravan,"{'geometric_mean': 14751, 'listings_count': 25...","{'geometric_mean': 47190, 'listings_count': 28...","{'geometric_mean': 44, 'listings_count': 29512..."
22,us,used,29389,GMC,Sierra 1500,"{'geometric_mean': 24451, 'listings_count': 26...","{'geometric_mean': 48596, 'listings_count': 28...","{'geometric_mean': 78, 'listings_count': 29389..."
23,us,used,27772,Jeep,Cherokee,"{'geometric_mean': 18294, 'listings_count': 26...","{'geometric_mean': 31840, 'listings_count': 26...","{'geometric_mean': 90, 'listings_count': 27772..."
24,us,used,27342,Ford,Edge,"{'geometric_mean': 17075, 'listings_count': 24...","{'geometric_mean': 45765, 'listings_count': 26...","{'geometric_mean': 70, 'listings_count': 27342..."
25,us,used,26465,Chevrolet,Cruze,"{'geometric_mean': 11256, 'listings_count': 23...","{'geometric_mean': 42136, 'listings_count': 25...","{'geometric_mean': 77, 'listings_count': 26465..."
26,us,used,25740,Toyota,Highlander,"{'geometric_mean': 22228, 'listings_count': 23...","{'geometric_mean': 43508, 'listings_count': 24...","{'geometric_mean': 52, 'listings_count': 25740..."
27,us,used,24917,Hyundai,Sonata,"{'geometric_mean': 11590, 'listings_count': 21...","{'geometric_mean': 49392, 'listings_count': 23...","{'geometric_mean': 66, 'listings_count': 24917..."
28,us,used,24642,Ford,Mustang,"{'geometric_mean': 18420, 'listings_count': 22...","{'geometric_mean': 32521, 'listings_count': 23...","{'geometric_mean': 77, 'listings_count': 24642..."
29,us,used,23398,Chevrolet,Tahoe,"{'geometric_mean': 24061, 'listings_count': 19...","{'geometric_mean': 66566, 'listings_count': 22...","{'geometric_mean': 62, 'listings_count': 23398..."
30,us,used,23212,Ford,F-250 Super Duty,"{'geometric_mean': 28787, 'listings_count': 19...","{'geometric_mean': 58579, 'listings_count': 22...","{'geometric_mean': 65, 'listings_count': 23212..."
31,us,used,22462,Chevrolet,Impala,"{'geometric_mean': 11945, 'listings_count': 18...","{'geometric_mean': 57765, 'listings_count': 21...","{'geometric_mean': 51, 'listings_count': 22462..."
32,us,used,22023,Kia,Optima,"{'geometric_mean': 13399, 'listings_count': 19...","{'geometric_mean': 42153, 'listings_count': 21...","{'geometric_mean': 61, 'listings_count': 22023..."
33,us,used,21967,BMW,3 Series,"{'geometric_mean': 17450, 'listings_count': 19...","{'geometric_mean': 37743, 'listings_count': 20...","{'geometric_mean': 79, 'listings_count': 21967..."
34,us,used,21943,Jeep,Wrangler Unlimited,"{'geometric_mean': 25865, 'listings_count': 19...","{'geometric_mean': 49794, 'listings_count': 21...","{'geometric_mean': 79, 'listings_count': 21943..."
35,us,used,20986,GMC,Acadia,"{'geometric_mean': 19920, 'listings_count': 18...","{'geometric_mean': 46952, 'listings_count': 20...","{'geometric_mean': 71, 'listings_count': 20986..."
36,us,used,20934,Chevrolet,Traverse,"{'geometric_mean': 18083, 'listings_count': 18...","{'geometric_mean': 48502, 'listings_count': 20...","{'geometric_mean': 77, 'listings_count': 20934..."
37,us,used,20570,Kia,Sorento,"{'geometric_mean': 15652, 'listings_count': 18...","{'geometric_mean': 46171, 'listings_count': 19...","{'geometric_mean': 61, 'listings_count': 20570..."
38,us,used,20547,Dodge,Journey,"{'geometric_mean': 14552, 'listings_count': 18...","{'geometric_mean': 39480, 'listings_count': 19...","{'geometric_mean': 75, 'listings_count': 20547..."
39,us,used,20514,Subaru,Outback,"{'geometric_mean': 18396, 'listings_count': 18...","{'geometric_mean': 36962, 'listings_count': 19...","{'geometric_mean': 51, 'listings_count': 20514..."
40,us,used,19810,Toyota,Tundra,"{'geometric_mean': 24860, 'listings_count': 17...","{'geometric_mean': 51651, 'listings_count': 19...","{'geometric_mean': 62, 'listings_count': 19810..."
41,us,used,19571,GMC,Terrain,"{'geometric_mean': 16499, 'listings_count': 18...","{'geometric_mean': 39541, 'listings_count': 18...","{'geometric_mean': 79, 'listings_count': 19571..."
42,us,used,19425,Volkswagen,Jetta,"{'geometric_mean': 11195, 'listings_count': 16...","{'geometric_mean': 41444, 'listings_count': 18...","{'geometric_mean': 55, 'listings_count': 19425..."
43,us,used,19301,Honda,Pilot,"{'geometric_mean': 18913, 'listings_count': 17...","{'geometric_mean': 54816, 'listings_count': 18...","{'geometric_mean': 51, 'listings_count': 19301..."
44,us,used,18848,Jeep,Compass,"{'geometric_mean': 16054, 'listings_count': 17...","{'geometric_mean': 29066, 'listings_count': 18...","{'geometric_mean': 73, 'listings_count': 18848..."
45,us,used,18597,Toyota,4Runner,"{'geometric_mean': 24562, 'listings_count': 17...","{'geometric_mean': 44553, 'listings_count': 18...","{'geometric_mean': 58, 'listings_count': 18597..."
46,us,used,18571,Volkswagen,Passat,"{'geometric_mean': 12395, 'listings_count': 16...","{'geometric_mean': 44780, 'listings_count': 17...","{'geometric_mean': 59, 'listings_count': 18571..."
47,us,used,18570,Kia,Soul,"{'geometric_mean': 11895, 'listings_count': 16...","{'geometric_mean': 38746, 'listings_count': 17...","{'geometric_mean': 59, 'listings_count': 18570..."
48,us,used,18138,Lexus,RX,"{'geometric_mean': 23794, 'listings_count': 16...","{'geometric_mean': 42323, 'listings_count': 17...","{'geometric_mean': 51, 'listings_count': 18138..."
49,us,used,18047,Subaru,Forester,"{'geometric_mean': 16465, 'listings_count': 16...","{'geometric_mean': 42061, 'listings_count': 16...","{'geometric_mean': 47, 'listings_count': 18047..."

In [11]:
# try another way of parsing json to data frame
df = pd.read_json(response.text, orient='records')

In [19]:
# still the same issue. data is not parsed all hte way to child element. Review price_stats value for example.
df.head()

,country,inventory_type,count,make,model,price_stats,miles_stats,dom_stats
0,us,used,102767,Ford,F-150,"{'geometric_mean': 22934, 'listings_count': 90...","{'geometric_mean': 49392, 'listings_count': 98...","{'geometric_mean': 68, 'listings_count': 10276..."
1,us,used,75449,Chevrolet,Silverado 1500,"{'geometric_mean': 22927, 'listings_count': 66...","{'geometric_mean': 50173, 'listings_count': 72...","{'geometric_mean': 77, 'listings_count': 75449..."
2,us,used,55030,Ford,Escape,"{'geometric_mean': 14049, 'listings_count': 48...","{'geometric_mean': 42128, 'listings_count': 52...","{'geometric_mean': 65, 'listings_count': 55030..."
3,us,used,53625,Toyota,Camry,"{'geometric_mean': 13956, 'listings_count': 47...","{'geometric_mean': 44454, 'listings_count': 51...","{'geometric_mean': 48, 'listings_count': 53625..."
4,us,used,49430,Chevrolet,Equinox,"{'geometric_mean': 14853, 'listings_count': 44...","{'geometric_mean': 41781, 'listings_count': 47...","{'geometric_mean': 63, 'listings_count': 49430..."

In [13]:
# use json library to normalize the json into dataframe
from pandas.io.json import json_normalize 

df1 = json_normalize(json_data)
df1.columns

C:\Users\SAgrawal\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  This is separate from the ipykernel package so we can avoid doing imports until

Index(['country', 'inventory_type', 'count', 'make', 'model',
       'price_stats.geometric_mean', 'price_stats.listings_count',
       'price_stats.min', 'price_stats.median',
       'price_stats.population_standard_deviation', 'price_stats.variance',
       'price_stats.max', 'price_stats.mean', 'price_stats.trimmed_mean',
       'price_stats.standard_deviation', 'price_stats.iqr',
       'miles_stats.geometric_mean', 'miles_stats.listings_count',
       'miles_stats.min', 'miles_stats.median',
       'miles_stats.population_standard_deviation', 'miles_stats.variance',
       'miles_stats.max', 'miles_stats.mean', 'miles_stats.trimmed_mean',
       'miles_stats.standard_deviation', 'miles_stats.iqr',
       'dom_stats.geometric_mean', 'dom_stats.listings_count', 'dom_stats.min',
       'dom_stats.median', 'dom_stats.population_standard_deviation',
       'dom_stats.variance', 'dom_stats.max', 'dom_stats.mean',
       'dom_stats.trimmed_mean', 'dom_stats.standard_deviation',
       'dom_stats.iqr'],
      dtype='object')

In [14]:
# finally looks like data is parsed into data frame to to child level
df1.head()

,country,inventory_type,count,make,model,price_stats.geometric_mean,price_stats.listings_count,price_stats.min,price_stats.median,price_stats.population_standard_deviation,...,dom_stats.listings_count,dom_stats.min,dom_stats.median,dom_stats.population_standard_deviation,dom_stats.variance,dom_stats.max,dom_stats.mean,dom_stats.trimmed_mean,dom_stats.standard_deviation,dom_stats.iqr
0,us,used,102767,Ford,F-150,22934,90156,499,26450,11368,...,102767,1,80,158,24894,2429,124,96,158,119
1,us,used,75449,Chevrolet,Silverado 1500,22927,66864,495,25995,9249,...,75449,1,93,162,26316,2514,134,107,162,127
2,us,used,55030,Ford,Escape,14049,48757,499,15495,7040,...,55030,1,77,147,21695,2371,114,89,147,104
3,us,used,53625,Toyota,Camry,13956,47486,499,15999,7837,...,53625,1,58,129,16709,2324,90,68,129,84
4,us,used,49430,Chevrolet,Equinox,14853,44495,499,16000,7080,...,49430,1,74,139,19305,2255,106,83,139,95

In [15]:
# find any duplicates
any(df1.duplicated())

False

In [16]:
any(df1.model.duplicated())

False

In [17]:
any(df1[['model','make']].duplicated())

False

In [18]:
# capitilize the data and cleanup the data casing issues
df1['make'] = df1.make.str.capitalize()
df1['model'] = df1.model.str.capitalize()
df1['country'] = df1.country.str.upper()
df1.head()

,country,inventory_type,count,make,model,price_stats.geometric_mean,price_stats.listings_count,price_stats.min,price_stats.median,price_stats.population_standard_deviation,...,dom_stats.listings_count,dom_stats.min,dom_stats.median,dom_stats.population_standard_deviation,dom_stats.variance,dom_stats.max,dom_stats.mean,dom_stats.trimmed_mean,dom_stats.standard_deviation,dom_stats.iqr
0,US,used,102767,Ford,F-150,22934,90156,499,26450,11368,...,102767,1,80,158,24894,2429,124,96,158,119
1,US,used,75449,Chevrolet,Silverado 1500,22927,66864,495,25995,9249,...,75449,1,93,162,26316,2514,134,107,162,127
2,US,used,55030,Ford,Escape,14049,48757,499,15495,7040,...,55030,1,77,147,21695,2371,114,89,147,104
3,US,used,53625,Toyota,Camry,13956,47486,499,15999,7837,...,53625,1,58,129,16709,2324,90,68,129,84
4,US,used,49430,Chevrolet,Equinox,14853,44495,499,16000,7080,...,49430,1,74,139,19305,2255,106,83,139,95

In [113]:
#plt.boxplot(df1.count, notch=True)
df1.count.str.unique()

AttributeError: 'function' object has no attribute 'str'